language: php
php:
  - 7.3

before_script:
 - composer self-update
 - composer update
 - composer install --prefer-source --no-interaction --dev
 
script: phpunit
 
fast_finish: true
language: php
sudo: false

cache:
 directories:
   - $HOME/.composer/cache/files
