language: php
php:
  - 7.3
  
env:
  global:
    - XDEBUG_MODE=coverage

before_script:
 - composer self-update
 - composer update
 - composer install --prefer-source --no-interaction --dev
 
script: phpunit --coverage-text
 
fast_finish: true
language: php
sudo: false

cache:
 directories:
   - $HOME/.composer/cache/files
